# Tan Tien Docker Configuration for Magento
# (https://github.com/tienntps09110/docker-magento)
#
# Version 1.0

version: '3.7'

services:
  app:
    image: nginx:1.19.6
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./storage/nginx/conf.d:/etc/nginx/conf.d
      # - ./storage/var/log/nginx/example.com-error.log:/var/log/nginx/example.com-error.log
      - ./src:/var/www/html
  
  phpfpm:
    image: magento/magento-cloud-docker-php:7.3-fpm-1.2.1
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - ./storage/var/lib/mysql:/var/lib/mysql
      - .docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025"
      - "8025:8025"
  
  redis:
    image: redis:5.0-alpine
    restart: always
    ports:
      - "6379:6379"

  elasticsearch:
    image: magento/magento-cloud-docker-elasticsearch:7.6-1.2.1
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"

  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    restart: always
    ports:
      - "25672:25672"
      - "5672:5672"
    volumes:
      - ./storage/var/lib/rabbitmq:/var/lib/rabbitmq